import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from './providers';
import Aside from "./components/aside";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="bg-gray-100  min-h-screen">
            <div className='block md:flex'>     
            <Aside />
            <div className='flex-grow bg-gray-100'>
            </div>
              {children}
            </div>
          </div>
          </Providers>
      </body>
    </html>
  );
}
